implement 01_basics_part_2 solution
DasneiN/wgforge_platform_frontend_course pull request #1
Opened 2019-04-03 17:51 UTC by DasneiN

2019-04-09 08:06 UTC, PavloKovalov requested changes

2019-04-09 08:06 UTC, PavloKovalov commented on 01_basics_part_2/practice/exercises/sleep.js
> +    if (!isNaN(s) && typeof s === 'number' && s > 0 && s % 1 === 0) {
переусложнил, есть метод Number для такой проверки

2019-04-09 08:06 UTC, PavloKovalov commented on 01_basics_part_2/practice/exercises/sleep.js
> +      void 0;
избыточно

2019-04-09 08:06 UTC, PavloKovalov commented on 01_basics_part_2/practice/exercises/smoosh.js
> +  if (isArray(arr)) {
лучше инвертировать условие и сделать `return`, чем тянуть отступы всего вложенного кода

2019-04-09 08:06 UTC, PavloKovalov commented on 01_basics_part_2/practice/exercises/smoosh.js
> +    function smooshInSqueeze(smooshArr) {
попробуй всё-таки сделать рекурсивно, без внутренней функции

2019-04-13 09:46 UTC, DasneiN commented
Corrected according to the review

2019-04-13 16:49 UTC, PavloKovalov approved these changes

2019-04-14 18:17 UTC, merged